
package net.sf.ehcache.server.soap.jaxws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "CacheException", targetNamespace = "http://soap.server.ehcache.sf.net/")
public class CacheException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CacheException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CacheException_Exception(String message, CacheException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public CacheException_Exception(String message, CacheException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.sf.ehcache.server.soap.jaxws.CacheException
     */
    public CacheException getFaultInfo() {
        return faultInfo;
    }

}
