package net.sf.ehcache.server.soap.jaxws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 */
@WebFault(name = "NoSuchCacheException", targetNamespace = "http://soap.server.ehcache.sf.net/")
public class NoSuchCacheException_Exception
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private NoSuchCacheException faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public NoSuchCacheException_Exception(String message, NoSuchCacheException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param message
     * @param cause
     */
    public NoSuchCacheException_Exception(String message, NoSuchCacheException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: net.sf.ehcache.server.soap.jaxws.NoSuchCacheException
     */
    public NoSuchCacheException getFaultInfo() {
        return faultInfo;
    }

}
